version: '3'

services:
  lawgg-crawling:
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_CONTAINER_NAME}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - lawgg-network
      - zabbix-net
    volumes:
      -  logs:/logs
    environment:
      - ACTIVE_PROFILE=${PROFILE}
    restart: unless-stopped

networks:
  lawgg-network:
    external: true
  zabbix-net:
    external: true

volumes:
  logs:
    external: true
